
apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: default
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: workload-identity-test
    command: ["sleep","infinity"]

---
apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test-1
  namespace: default
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: workload-identity-test-2
    command: ["sleep","infinity"]